### ISSUE TITLE
 Fullscreen ad fails to close. SDK 9.0.2

### ISSUE THREAD

**Issue by Str4tos** [loopme/android-united-sdk#110]
Hello,

I'm using SDK version 9.0.2 and I've encountered an issue with closing fullscreen ads. The ad loads successfully, but I always end up with a black screen that I can't close. 

My device is a Google Pixel 7 running Android 14.

I simply cloned your repository, made no modifications, and ran the Interstitial Sample. Below, I'll attach logs from the device and a video.

Please assist in resolving this issue.

[Downlaod Device logs LoopMeInterstitialErrorLog.txt](https://github.com/user-attachments/files/15530358/LoopMeInterstitialErrorLog.txt)

https://github.com/loopme/android-united-sdk/assets/22005013/77b7c499-a1a8-4a27-9993-fcf629f775a3

**Comment by bzarzoza** [comment]
Thank you for the detailed report. We will address and follow up.

**Comment by EpanchinE** [comment]
@Str4tos Thank you. 
Seems like this issue appeared for Android API >= 34
Fix merged: https://github.com/loopme/android-united-sdk/pull/111
